### ISSUE TITLE
Rescheduling does not copy the details of previous appointment

### ISSUE THREAD

**Issue by md-azsa** [CS2103JAN2018-F09-B4/main#239]
## Recreating
Create an appointment -> add a pet or assign a vet tech to that appointment -> call reschedule command

## Images
![reschedule_error1](https://user-images.githubusercontent.com/25269615/38548426-5c3bf418-3ce4-11e8-835b-f3a0f4136a95.PNG)

![reschedule_error2](https://user-images.githubusercontent.com/25269615/38548435-60e61228-3ce4-11e8-9328-851dc2d1ab2c.PNG)

## Possible error
Failed to copy the entire object after rescheduling.

**Comment by Godxin** [comment]
Cause an appointment does not have client and pet vet tech, it only copies date, time, duration and description which are inside appointment class.

**Comment by jonathanwj** [comment]
Resolved
