### ISSUE TITLE
Clear addressbook does clear listall panel

### ISSUE THREAD

**Issue by jonathanwj** [CS2103JAN2018-F09-B4/main#251]
i listed 2 person before clearing

![image](https://user-images.githubusercontent.com/29134984/38652708-bb1bb008-3e39-11e8-8821-e6c49d1db169.png)

**Comment by md-azsa** [comment]
@purplepers0n raised up this issue before. Not sure if it's fixed. Are you on the latest pull?

**Comment by jonathanwj** [comment]
I believe i am on the latest pull.
![2018-04-12_10-53-04](https://user-images.githubusercontent.com/29134984/38653968-cc372b96-3e3f-11e8-8bc9-36ad1342fa8f.gif)

**Comment by purplepers0n** [comment]
Ah I see that if you list twice it will not clear properly. Noted, I will fix this bug and make another PR
